name: build, deploy mvc in main server
on: 
  push: 
    branches:
      - main
jobs:
  create_env_file:
    name: import env file
    runs-on: ubuntu-latest
    steps:
      - name: create .env file
        run: |
          echo "DB_HOST=$DB_HOST" > .env
          echo "DB_PORT=$DB_PORT" >> .env
          echo "DB_USERNAME=$DB_USERNAME" >> .env
          echo "DB_PASSWORD=$DB_PASSWORD" >> .env
          echo "DB_NAME=$DB_NAME" >> .env
        shell: bash
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}

      - name: show contents of .env
        run: cat .env

  build_docker:
    name: build and push to docker hub
    runs-on: ubuntu-latest
    needs: create_env_file
    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: docker build -t fadilahonespot/simple-mvc:1.1.0 . 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push to docker hub
        run: docker push fadilahonespot/simple-mvc:1.1.0
  deploy: 
    name: deployment to EC2 server
    runs-on: ubuntu-latest
    needs: build_docker
    steps: 
      - uses: actions/checkout@v3
      - name: login to EC2
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_USER: ${{secrets.USER_NAME}}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/fadilah.pem
          chmod 400 ~/.ssh/fadilah.pem
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/fadilah.pem
            StrictHostKeyChecking=no
          END
      - name: run script deployment
        run: |
          ssh staging 'docker pull $DOCKER_IMAGE && docker stop $DOCKER_CONTAINER && docker rm $DOCKER_CONTAINER && docker run -d -p $PORT --name $DOCKER_CONTAINER $DOCKER_IMAGE'
        env:
          DOCKER_IMAGE: fadilahonespot/simple-mvc:1.1.0
          DOCKER_CONTAINER: simpe-mvc-apps
          PORT: 8000:8000

