name: build, deploy mvc in main server
on: 
  push: 
    branches:
      - main
jobs:
  build_docker:
    name: build and push to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: docker build -t fadilahonespot/simple-mvc:1.1.0 . 

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push to docker hub
        run: docker push fadilahonespot/simple-mvc:1.1.0

  deploy:
    runs-on: ubuntu-latest
    needs: build_docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ./key.pem
          script: |
            # Pull the Docker image from the registry
            docker pull fadilahonespot/simple-mvc:1.1.0
            
            # Stop and remove any existing container (optional)
            docker stop simpe-mvc-apps || true
            docker rm simpe-mvc-apps || true

            # Set MySQL configuration as environment variables
            export MYSQL_DB_HOST=${{ secrets.DB_HOST }}
            export MYSQL_DB_USER=${{ secrets.DB_USERNAME }}
            export MYSQL_DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export MYSQL_DB_PORT=${{ secrets.DB_PORT }}
            export MYSQL_DB_NAME=${{ secrets.DB_NAME }}

            # Run the Docker container with MySQL environment variables
            docker run -d -p 8000:8000 \
              -e MYSQL_DB_HOST \
              -e MYSQL_DB_USER \
              -e MYSQL_DB_PASSWORD \
              -e MYSQL_DB_PORT \
              -e MYSQL_DB_NAME \
              --name simpe-mvc-apps \
              fadilahonespot/simple-mvc:1.1.0

  # deploy: 
  #   name: deployment to EC2 server
  #   runs-on: ubuntu-latest
  #   needs: build_docker
  #   steps: 
  #     - uses: actions/checkout@v3
  #     - name: login to EC2
  #       env:
  #         SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #         SSH_HOST: ${{secrets.SSH_HOST}}
  #         SSH_USER: ${{secrets.USER_NAME}}
  #       run: |
  #         mkdir -p ~/.ssh/
  #         echo "$SSH_KEY" > ~/.ssh/fadilah.pem
  #         chmod 400 ~/.ssh/fadilah.pem
  #         cat >>~/.ssh/config <<END
  #         Host staging
  #           HostName $SSH_HOST
  #           User $SSH_USER
  #           IdentityFile ~/.ssh/fadilah.pem
  #           StrictHostKeyChecking=no
  #         END
  #     - name: run script deployment
  #       env:
  #         DB_HOST: ${{ secrets.DB_HOST }}
  #         DB_PORT: ${{ secrets.DB_PORT }}
  #         DB_USERNAME: ${{ secrets.DB_USERNAME }}
  #         DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  #         DB_NAME: ${{ secrets.DB_NAME }}
  #       run: |
  #         ssh staging 'docker pull fadilahonespot/simple-mvc:1.1.0 && docker stop simpe-mvc-apps && docker rm simpe-mvc-apps && docker run -e DB_HOST=$DB_HOST -e DB_PORT=$DB_PORT -e DB_USERNAME=$DB_USERNAME -e DB_PASSWORD=$DB_PASSWORD -e DB_NAME=$DB_NAME -d -p 8000:8000 --name simpe-mvc-apps fadilahonespot/simple-mvc:1.1.0'

