name: build, deploy mvc in main server
on: 
  push: 
    branches:
      - main
jobs:
  create_env:
    name: import env file
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_DB_PORT: ${{ secrets.DB_PORT }}
          envkey_DB_USERNAME: ${{ secrets.DB_USERNAME }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_NAME: ${{ secrets.DB_NAME }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false
  build_docker:
    name: build and push to docker hub
    runs-on: ubuntu-latest
    needs: create_env
    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: docker build -t fadilahonespot/simple-mvc:1.1.0 .     
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push to docker hub
        run: docker push fadilahonespot/simple-mvc:1.1.0
  deploy: 
    name: deployment to EC2 server
    runs-on: ubuntu-latest
    needs: build_docker
    steps: 
      - uses: actions/checkout@v3
      - name: login to EC2
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_USER: ${{secrets.USER_NAME}}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/fadilah.pem
          chmod 400 ~/.ssh/fadilah.pem
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/fadilah.pem
            StrictHostKeyChecking=no
          END      
      - name: docker pull and running container
        run: ssh staging 'docker rm -f $(docker ps -a -q) && docker pull fadilahonespot/simple-mvc:1.1.0 && docker run -d -p 8000:8000 --name simpe-mvc-apps fadilahonespot/simple-mvc:1.1.0' 
